---
- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: true
  notify:
    - activate_firewall

- meta: flush_handlers

- name: Enable and Start Nginx Service
  systemd: name=nginx enabled=yes state=started


- name: allow Nginx Port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: allow Port 22
  ufw:
    rule: allow
    port: '22'
    proto: tcp
  notify:
    - reload_firewall

- meta: flush_handlers
